GENERAL = "GENERAL"
PRIVATE = "PRIVATE"
CONVERSATION_TYPES = {GENERAL, PRIVATE}

CHAT_MESSAGE_CREATED = "CHAT_MESSAGE_CREATED"
CHAT_MESSAGE_EDITED = "CHAT_MESSAGE_EDITED"
CHAT_MESSAGE_DELETED = "CHAT_MESSAGE_DELETED"
EVENT_VERSION = 1

SOCKET_CHAT_JOIN = "chat_join"
SOCKET_CHAT_LEAVE = "chat_leave"
SOCKET_CHAT_SEND = "chat_send_message"
SOCKET_CHAT_EDIT = "chat_edit_message"
SOCKET_CHAT_DELETE = "chat_delete_message"
SOCKET_CHAT_CREATED = "chat_message_created"
SOCKET_CHAT_EDITED = "chat_message_edited"
SOCKET_CHAT_DELETED = "chat_message_deleted"
SOCKET_CHAT_ERROR = "chat_error"
